# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7832881507e2f25a23ca7a3d7ddcb0fbe8f94fb0d66f8005c7f84913d7479130dcc3caca85034d422e3cf3caf30daaafbd8fce41b5fecfac5ab0a45217a9bc9

test:
  secret_key_base: b3c2a1b7005fa53fe8fc013fd3c1438b6ff7b97c8fc9c778dcac1a579fe4957709b4cdb1a92344211a3a008989fc8c352a049fa0ddcdf0afa09637fa3cdc9c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
